git log origin/dev --since=15.weeks --until=14.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat1.csv
git log origin/dev --since=14.weeks --until=13.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat2.csv
git log origin/dev --since=13.weeks --until=12.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat3.csv
git log origin/dev --since=12.weeks --until=11.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat4.csv
git log origin/dev --since=11.weeks --until=10.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat5.csv
git log origin/dev --since=10.weeks --until=9.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat6.csv
git log origin/dev --since=9.weeks --until=8.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat7.csv
git log origin/dev --since=8.weeks --until=7.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat8.csv
git log origin/dev --since=7.weeks --until=6.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat9.csv
git log origin/dev --since=6.weeks --until=5.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat10.csv
git log origin/dev --since=5.weeks --until=4.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat11.csv
git log origin/dev --since=4.weeks --until=3.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat12.csv
git log origin/dev --since=3.weeks --until=2.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat13.csv
git log origin/dev --since=2.weeks --until=1.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat14.csv
git log origin/dev --since=1.weeks --numstat --pretty="%ae %H" | sed 's/@.*//g' | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name", "plus[name]", "minus[name]}}' | sort -k2 -gr > gitStat15.csv